### ISSUE TITLE
secret.json doesn't exist

### ISSUE THREAD

**Issue by eastcoastcoder** [SujeethJinesh/react-native-dynamic-graph#1]
Is there any way to continue without it?

**Comment by SujeethJinesh** [comment]
Hi Ethan!

I have a fix coming up really soon (currently traveling). I haven't published this full repo on npm yet. But it'll be ready in about a week.

Edit: turns out I made those changes but didn't push. I have pushed them now, so you should be able to run the commands and display a sample graph which you can play with.

Thanks,
Sujeeth Jinesh
